<?php

putenv('DISPLAY_ERROS_DETAILS=true');
putenv('GERENCIADOR_DE_LOJA_MYSQL_HOST=localhost');
putenv('GERENCIADOR_DE_LOJA_MYSQL_DBNAME=gerenciador_de_loja');
putenv('GERENCIADOR_DE_LOJA_MYSQL_USER=root');
putenv('GERENCIADOR_DE_LOJA_MYSQL_PASSWORD=');
putenv('GERENCIADOR_DE_LOJA_MYSQL_PORT=3306');



?>